language: node_js
node_js:
  - "12.3.1"
  - "12.0.0"
  - "11.15.0"
  - "11.0.0"
  - "10.15.3"
  - "10.0.0"
  - "9.11.2"
  - "9.0.0"
  - "8.16.0"
  - "8.0.0"
  - "7.10.1"
  - "7.0.0"
  - "6.17.1"
  - "6.0.0"
script:
  - npm test
